name: Deploy Hugo site to GitHub Pages

# 只要给 push gh-pages 分支所需的写权限
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 把整个仓库和子模块（theme）都检出，fetch-depth 设 0 保留完整历史
      - name: Checkout source with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. 安装 Hugo Extended
      - name: Setup Hugo Extended
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.147.9"
          extended: true

      # 3. 构建到 public/
      - name: Build Hugo site
        run: hugo --minify

      # 4. 推送 public/ 到 gh-pages 分支
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # 对本仓库有写权限的 Token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          # 如果想保留 gh-pages 上的其他文件改成 true
          keep_files: false
