name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: "Checkout source"
        uses: actions/checkout@v4

      # 2. Setup Hugo Extended for SCSS/SASS support
      - name: "Setup Hugo Extended"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.147.9"
          extended: true

      # 3. Build the Hugo site
      - name: "Build"
        run: hugo --minify

      # 4. Deploy to GitHub Pages
      - name: "Deploy to GitHub Pages"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true

